/**
 * ISWAdminAPI.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.actualogic.www.schema.SWAdminAPI;

public interface ISWAdminAPI extends java.rmi.Remote {
    public void ping(javax.xml.rpc.holders.CalendarHolder timestamp, javax.xml.rpc.holders.StringHolder serverVersion) throws java.rmi.RemoteException;
    public void addCompanyPayment(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.PaymentDetailsType paymentDetails, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public long getCompanyBalance(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId) throws java.rmi.RemoteException;
    public void addCompany(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.CompanyDetailsType companyDetails, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public void modifyCompany(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.CompanyDetailsType companyDetails, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public void addService(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.ServiceKeyType serviceKey, com.actualogic.www.schema.SWAdminAPI.types.ServiceDetailsType serviceDetails, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public void modifyService(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.ServiceKeyType serviceKey, com.actualogic.www.schema.SWAdminAPI.types.ServiceDetailsType serviceDetails, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public void removeService(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.ServiceKeyType serviceKey, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public void addServicePayment(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.ServiceKeyType serviceKey, com.actualogic.www.schema.SWAdminAPI.types.PaymentDetailsType paymentDetails, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public com.actualogic.www.schema.SWAdminAPI.types.CdrEntryType[] getCDR(com.actualogic.www.schema.SWAdminAPI.types.CdrRequestType cdrRequest) throws java.rmi.RemoteException;
    public com.actualogic.www.schema.SWAdminAPI.types.CdrEntryExType[] getCDR2(com.actualogic.www.schema.SWAdminAPI.types.Cdr2RequestType cdr2Request) throws java.rmi.RemoteException;
    public com.actualogic.www.schema.SWAdminAPI.TariffResponseType getTariff(com.actualogic.www.schema.SWAdminAPI.TariffRequestType tariffRequest) throws java.rmi.RemoteException;
    public com.actualogic.www.schema.SWAdminAPI.CustomerProfilesResponseType getCustomerProfiles(com.actualogic.www.schema.SWAdminAPI.CustomerProfilesRequestType customerProfilesRequest) throws java.rmi.RemoteException;
    public long getServiceBalance(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.ServiceKeyType serviceKey) throws java.rmi.RemoteException;
    public boolean isCompanyExist(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId) throws java.rmi.RemoteException;
    public boolean isServiceExist(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.ServiceKeyType serviceKey) throws java.rmi.RemoteException;
    public void addCardPayment(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.CardKeyType cardKey, com.actualogic.www.schema.SWAdminAPI.types.PaymentDetailsType paymentDetails, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public void addDDI(com.actualogic.www.schema.SWAdminAPI.types.DdiKeyType ddiKey, com.actualogic.www.schema.SWAdminAPI.types.DdiDetailsType ddiDetails, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public void modifyDDI(com.actualogic.www.schema.SWAdminAPI.types.DdiKeyType ddiKey, com.actualogic.www.schema.SWAdminAPI.types.DdiDetailsType ddiDetails, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public void removeDDI(com.actualogic.www.schema.SWAdminAPI.types.DdiKeyType ddiKey, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public boolean isDDIExist(com.actualogic.www.schema.SWAdminAPI.types.DdiKeyType ddiKey) throws java.rmi.RemoteException;
    public void addQuickNumber(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.QuickNumberKeyType quickNumberKey, com.actualogic.www.schema.SWAdminAPI.types.QuickNumberDetailsType quickNumberDetails, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public void modifyQuickNumber(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.QuickNumberKeyType quickNumberKey, com.actualogic.www.schema.SWAdminAPI.types.QuickNumberDetailsType quickNumberDetails, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public void removeQuickNumber(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.QuickNumberKeyType quickNumberKey, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public boolean isQuickNumberExist(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.QuickNumberKeyType quickNumberKey) throws java.rmi.RemoteException;
    public com.actualogic.www.schema.SWAdminAPI.types.CardProfileType[] getCardProfiles(com.actualogic.www.schema.SWAdminAPI.CustomerProfilesRequestType customerProfilesRequest) throws java.rmi.RemoteException;
    public boolean isCardExist(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.CardKeyType cardKey) throws java.rmi.RemoteException;
    public com.actualogic.www.schema.SWAdminAPI.GenerateCardsResponseType generateCards(com.actualogic.www.schema.SWAdminAPI.GenerateCardsRequestType generateCardsRequest) throws java.rmi.RemoteException;
    public com.actualogic.www.schema.SWAdminAPI.types.ServiceDetailsType getServiceDetails(com.actualogic.www.schema.SWAdminAPI.types.AgentCompanyIdType agentCompanyId, com.actualogic.www.schema.SWAdminAPI.types.ServiceKeyType serviceKey) throws java.rmi.RemoteException;
    public com.actualogic.www.schema.SWAdminAPI.types.CostProfileType[] getProfilesList(com.actualogic.www.schema.SWAdminAPI.ProfileListRequestType getProfilesListRequest) throws java.rmi.RemoteException;
    public void offerCompanyAssign(com.actualogic.www.schema.SWAdminAPI.OfferCompanyAssignRequestType offerCompanyAssignRequest, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public void offerServiceAssign(com.actualogic.www.schema.SWAdminAPI.OfferServiceAssignRequestType offerServiceAssignRequest, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public void offerCardAssign(com.actualogic.www.schema.SWAdminAPI.OfferCardAssignRequestType offerCardAssignRequest, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public void offerAddPayment(com.actualogic.www.schema.SWAdminAPI.OfferAddPaymentRequestType offerAddPaymentRequest, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
    public com.actualogic.www.schema.SWAdminAPI.OfferAssignedDetailsType[] offerGetAssigned(com.actualogic.www.schema.SWAdminAPI.OfferGetAssignedRequestType offerGetAssignedRequest) throws java.rmi.RemoteException;
    public void offerSetExpiryDate(com.actualogic.www.schema.SWAdminAPI.OfferSetExpiryDateRequestType offerSetExpiryDateRequest, javax.xml.rpc.holders.IntHolder status, javax.xml.rpc.holders.IntHolder errorCode, javax.xml.rpc.holders.StringHolder errorDescription) throws java.rmi.RemoteException;
}
